<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tb3_patrol</name>
  <version>1.0.0</version>
  <description>TurtleBot3 自主巡检包：代码驱动的多目标点导航（Nav2），支持一键启动、动态避障与导航恢复。</description>
  <maintainer email="qiaoruihao20061203@qq.com">qiao</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>nav2_simple_commander</exec_depend>
  <exec_depend>gazebo_msgs</exec_depend>
  <exec_depend>turtlebot3_gazebo</exec_depend>
  <exec_depend>turtlebot3_navigation2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
